stages:

  data_ingestion:
    cmd: python -m src.components.data_ingestion
    deps:
      - src/components/data_ingestion.py
      - config/config.yaml
      - data/raw/data.csv
    outs:
      - data/processed/train.csv
      - data/processed/test.csv

  data_transformation:
    cmd: python -m src.components.data_transformation
    deps:
      - src/components/data_transformation.py
      - config/config.yaml
      - data/processed/train.csv
      - data/processed/test.csv
    outs:
      - artifacts/preprocessor.pkl
      - artifacts/X_train.npy
      - artifacts/X_test.npy
      - artifacts/y_train.npy
      - artifacts/y_test.npy

  model_training:
    cmd: python -m src.components.model_trainer
    deps:
      - src/components/model_trainer.py
      - src/utils.py
      - params.yaml
      - config/config.yaml
      - artifacts/preprocessor.pkl
      - artifacts/X_train.npy
      - artifacts/X_test.npy
      - artifacts/y_train.npy
      - artifacts/y_test.npy
    outs:
      - artifacts/model.pkl